"""DO NOT MODIFY. Auto-generated by script/fingerprint_frontend."""

FINGERPRINTS = {
    "compatibility.js": "c679589d32e0588becbf104d9907e96a",
    "core.js": "4073d1aa7a9367ac39f33f43c34b51c9",
    "frontend.html": "ee6302092a992524b6ff689974121ab9",
    "mdi.html": "4921d26f29dc148c3e8bd5bcd8ce5822",
    "micromarkdown-js.html": "93b5ec4016f0bba585521cf4d18dec1a",
    "panels/ha-panel-config.html": "e14abf7ed39f9b0f75c33b6dd22b7786",
    "panels/ha-panel-dev-event.html": "2db9c218065ef0f61d8d08db8093cad2",
    "panels/ha-panel-dev-info.html": "61610e015a411cfc84edd2c4d489e71d",
    "panels/ha-panel-dev-service.html": "f55d58ffb462c35986e872ae8849af4f",
    "panels/ha-panel-dev-state.html": "d70314913b8923d750932367b1099750",
    "panels/ha-panel-dev-template.html": "41cf1dc8c465a240dc1674e27ceccf59",
    "panels/ha-panel-history.html": "361c00f0473fcb7ae56cfa09885f39ad",
    "panels/ha-panel-iframe.html": "d920f0aa3c903680f2f8795e2255daab",
    "panels/ha-panel-logbook.html": "a980cfe0b1eb0031f582896d33a94741",
    "panels/ha-panel-map.html": "9aa065b1908089f3bb5af7fdf9485be5",
    "websocket_test.html": "575de64b431fe11c3785bf96d7813450"
}
